# Generated by Django 4.1.5 on 2023-01-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snacks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="snack",
            old_name="reviewer",
            new_name="purchaser",
        ),
        migrations.RemoveField(
            model_name="snack",
            name="rating",
        ),
        migrations.AddField(
            model_name="snack",
            name="description",
            field=models.TextField(default="0", max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="snack",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
